@startuml controlled-proxy

skinparam DefaultTextAlignment left

allowmixing

left to right direction

actor " " as dev

circle "[controlProp]]" as controlInterface #LightBlue
note top of controlInterface
  {
    foo: true,
    bar: false,
    baz: true
    qux: false
  }
end note
dev --> controlInterface: runtime

circle "[disabledMemberHandlerProp]]" as disabledInterface #LightBlue
note bottom of disabledInterface
  default: () => undefined
end note
dev --> disabledInterface: runtime

circle "foo" as proxyFoo #LightGreen
note left of proxyFoo
  **controlled property ON**
  returns target.foo
end note

circle "bar" as proxyBar #LightPink
note left of proxyBar 
  **controlled property OFF**
  returns undefined
end note

circle "baz(...args)" as proxyBaz #LightGreen
note left of proxyBaz 
  **controlled method ON**
  returns target.baz(...args)
end note

circle "qux(...args)" as proxyQux #LightPink
note left of proxyQux 
  **controlled method OFF**
  returns undefined
end note

circle "thud" as proxyThud #LightGreen
note left of proxyThud 
  **uncontrolled member**
  returns target.thud
end note

object "controlledProxy(target)" as proxy #LightBlue

controlInterface -- proxy 
disabledInterface -- proxy 
proxyFoo -- proxy
proxyBar -- proxy
proxyBaz -- proxy
proxyQux -- proxy
proxyThud -- proxy

object "target" as target
circle "foo" as targetFoo
circle "bar" as targetBar
circle "baz(...args)" as targetBaz
circle "qux(...args)" as targetQux
circle "thud" as targetThud

target -- targetFoo
target -- targetBar
target -- targetBaz
target -- targetQux
target -- targetThud

proxy <|-- target

@enduml